### PR TITLE
Add LUNATIC_INDEX global variable

### PR DESCRIPTION
**Pull request by Grafikart**
Add a global variable to display the current iteration in VTL expression.

For instance 

```js
"label": {
    "value": "\"Questions 1, Itération : \" || LUNATIC_INDEX",
    "type": "VTL"
},
```

### CODE REVIEW

**Comment by ddecrulle** [comment]
What happens if this variable is used outside a loop context? Probably undefined, but it might be interesting to raise an error ?

**Comment by isMattCoding** [comment]
I tested in Stromae-v3, this solution looks like it works well inside of a paginated loop, which is sufficient for our requirements. 
I tested in block for loop, roundabout and summary, and it seems to work as expected. 
When outside of a loop, in a non-iterative context, the variable displays as `1`.  I agree with @ddecrulle that it's worth adding a conditional error message if the iteration is undefined.

**Comment by jdirand** [comment]
The variable should be called global_iteration_index and the default value should be 1 as discussed.

**Comment by ddecrulle** [comment]
@romaintailhurat choses `GLOBAL_ITERATION_INDEX`

**Comment by romaintailhurat** [comment]
> @romaintailhurat choses `GLOBAL_ITERATION_INDEX`

Yes, uppercase is better.

**Review by ddecrulle — APPROVED** [review]

**Pull request merged**
