### PR TITLE
I18n for modal => add in dictionary

### PR DESCRIPTION
**Pull request by MickaelMenet**

### CODE REVIEW

**Comment by ddecrulle** [comment]
Can you explain how you detect the lang ?

**Comment by MickaelMenet** [comment]
> Can you explain how you detect the lang ?
Using the existing in the build-dictionary.js file, also present in stromae.

**Comment by ddecrulle** [comment]
> > Can you explain how you detect the lang ?
> 
> Using the existing in the build-dictionary.js file, also present in stromae.
> 
> 

Did you notice that you are on lunatic repository ?

**Comment by MickaelMenet** [comment]
> > > Can you explain how you detect the lang ?
> > 
> > 
> > Using the existing in the build-dictionary.js file, also present in stromae.
> 
> Did you notice that you are on lunatic repository ?

Yes, the system for retrieving the browser language is used in both directories. This is what I meant in my previous comment.

**Comment by ddecrulle** [comment]
But lunatic is not supposed to use i18n and it's not beacause stromae had a build-dictionnary.js that this will works

**Comment by MickaelMenet** [comment]
> What's happens in storybook ?

image
image

**Comment by ddecrulle** [comment]
Ok I did not know that lunatic had also a build-dictionary. I think this is not the responsibility to lunatic to did that but yes it works

**Pull request merged**
